//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcija
    {
        public int id { get; set; }
        public string nazivTransakcije { get; set; }
        public Nullable<decimal> kvantitetTransakcije { get; set; }
        public Nullable<int> karticaId { get; set; }
    
        public virtual Kartica Kartica { get; set; }
    }
}
